
services:
  backend:
    build: ./backend
    container_name: mainbackend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
  frontend:
    build: ./frontend
    container_name: mainfrontend
    ports:
      - "5173:80"
      
  online-compiler:
    build: ./online-compiler/backend
    container_name: maincompiler
    ports:
      - "8000:8000"
    env_file:
      - ./online-compiler/backend/.env